"""add staff_name to requirement

Revision ID: 41a8aa8d1c62
Revises: 6baf04d4251d
Create Date: 2025-09-01 21:33:27.879464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41a8aa8d1c62'
down_revision = '6baf04d4251d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_name', sa.String(), nullable=False, server_default='Unassigned'))
        batch_op.create_index(batch_op.f('ix_requirements_staff_name'), ['staff_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirements_staff_name'))
        batch_op.drop_column('staff_name')

    # ### end Alembic commands ###
