"""add is_admin to users

Revision ID: 4a40dea0b7e2
Revises: 41a8aa8d1c62
Create Date: 2025-09-01 22:01:55.748763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a40dea0b7e2'
down_revision = '41a8aa8d1c62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_users_is_admin'), ['is_admin'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_admin'))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
