"""add image to requirement

Revision ID: 6baf04d4251d
Revises: b374ff1d2d25
Create Date: 2025-09-01 21:19:22.373218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6baf04d4251d'
down_revision = 'b374ff1d2d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
